# Generated by Django 3.1.14 on 2022-11-17 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'in'), ('out', 'out')], default='in', max_length=8)),
                ('app_name', models.CharField(max_length=128)),
                ('label', models.CharField(db_index=True, max_length=128)),
                ('ip', models.CharField(blank=True, max_length=128, null=True)),
                ('http_method', models.CharField(choices=[('options', 'options'), ('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], db_index=True, max_length=8)),
                ('uri', models.CharField(max_length=1024)),
                ('status_code', models.SmallIntegerField()),
                ('request', models.JSONField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
