#!/bin/bash
psql -a -e --username root -c "CREATE ROLE $CGRATES_GATEWAY_DATABASES_DEFAULT_USER WITH LOGIN ENCRYPTED PASSWORD '$CGRATES_GATEWAY_DATABASES_DEFAULT_PASSWORD';"
psql -a -e --username root -c "CREATE DATABASE $CGRATES_GATEWAY_DATABASES_DEFAULT_NAME OWNER =  $CGRATES_GATEWAY_DATABASES_DEFAULT_USER;"
psql -a -e --username root -c "ALTER USER $CGRATES_GATEWAY_DATABASES_DEFAULT_USER CREATEDB;"
psql -a -e --username root -c "CREATE ROLE $CGRATES_GATEWAY_DATABASES_LOG_USER WITH LOGIN ENCRYPTED PASSWORD '$CGRATES_GATEWAY_DATABASES_LOG_PASSWORD';"
psql -a -e --username root -c "CREATE DATABASE $CGRATES_GATEWAY_DATABASES_LOG_NAME OWNER =  $CGRATES_GATEWAY_DATABASES_LOG_USER;"
psql -a -e --username root -c "ALTER USER $CGRATES_GATEWAY_DATABASES_LOG_USER CREATEDB;"